export const DOMAIN_CONSTANTS = {
  DEFAULT_SLOT_DURATION_MINUTES: 50,
  DEFAULT_BUFFER_DURATION_MINUTES: 10,
  DEFAULT_PAGE_SIZE: 10,
  DEFAULT_DASHBOARD_LIMIT: 5,
  PASSWORD_SALT_ROUNDS: 10,
  REFRESH_TOKEN_BYTE_LENGTH: 64,
  SLOT_HOLD_DURATION_SECONDS: 60,
} as const;
